# Generated by Django 5.2.9 on 2025-12-26 17:43

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0009_delete_instance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Instance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for the instance",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=120)),
                (
                    "image_name",
                    models.CharField(
                        default="willFail:fail",
                        help_text="Docker image name, e.g., nginx:latest",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("exited", "Exited"),
                            ("stopped", "Stopped"),
                            ("destroyed", "Destroyed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "container_port",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Container Port used for this instance",
                        null=True,
                    ),
                ),
                (
                    "host_port",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Host Port used for this instance",
                        null=True,
                    ),
                ),
                (
                    "environment",
                    models.JSONField(
                        blank=True, help_text="Environment variables used", null=True
                    ),
                ),
                (
                    "default_restart_policy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no", "No"),
                            ("on-failure", "On failure"),
                            ("always", "Always"),
                            ("unless-stopped", "Unless stopped"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "container_id",
                    models.CharField(
                        blank=True,
                        help_text="Docker container ID",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "docker_output",
                    models.JSONField(
                        blank=True, help_text="Docker API output or metadata", null=True
                    ),
                ),
                (
                    "pangolin_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("pangolin_resource_domain", models.URLField(blank=True, null=True)),
                (
                    "pangolin_protocol",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "pangolin_target_protocol",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("pangolin_port", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="catalog.module",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="instances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="unique_instance_name",
                        violation_error_message="This instance name is already in use.",
                    )
                ],
            },
        ),
    ]
