# Generated by Django 5.2.8 on 2025-11-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serviceCatalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tf_module",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
