# Generated by Django 5.2.8 on 2025-11-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("serviceCatalog", "0002_tf_module_slug"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TF_Module",
            new_name="Module",
        ),
    ]
