# Generated by Django 5.2.8 on 2025-11-12 14:18

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serviceCatalog", "0003_rename_tf_module_module"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instance",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="module",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="instance",
            name="terraform_output",
        ),
        migrations.RemoveField(
            model_name="module",
            name="module_code",
        ),
        migrations.AddField(
            model_name="instance",
            name="container_id",
            field=models.CharField(
                blank=True, help_text="Docker container ID", max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="docker_output",
            field=models.JSONField(
                blank=True, help_text="Docker API output or metadata", null=True
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="environment",
            field=models.JSONField(
                blank=True, help_text="Environment variables used", null=True
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="ports",
            field=models.JSONField(
                blank=True, help_text="Port mapping used for this instance", null=True
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="restart_policy",
            field=models.JSONField(
                blank=True, help_text="Restart policy used", null=True
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="default_env",
            field=models.JSONField(
                blank=True,
                help_text="Default environment variables, e.g., {'ENV_VAR': 'value'}",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="default_ports",
            field=models.JSONField(
                blank=True,
                help_text="Default port mapping, e.g., {'80/tcp': 8080}",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="default_restart_policy",
            field=models.JSONField(
                blank=True,
                help_text="Default restart policy, e.g., {'Name': 'always'}",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="image_name",
            field=models.CharField(
                default="willFail:fail",
                help_text="Docker image name, e.g., nginx:latest",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="serviceCatalog.module",
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="name",
            field=models.CharField(
                help_text="Unique name for the instance", max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="instances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("failed", "Failed"),
                    ("stopped", "Stopped"),
                    ("destroyed", "Destroyed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="description",
            field=models.TextField(
                blank=True, help_text="Short description of the module"
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="name",
            field=models.CharField(
                help_text="Name of the module", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="quota",
            field=models.PositiveIntegerField(
                default=3, help_text="Maximum number of instances user can create"
            ),
        ),
        migrations.AlterConstraint(
            model_name="instance",
            name="unique_instance_name",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="unique_instance_name",
                violation_error_message="This instance name is already in use.",
            ),
        ),
    ]
