# Generated by Django 5.2.8 on 2025-11-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serviceCatalog", "0004_alter_instance_options_alter_module_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="image_name",
            field=models.CharField(
                default="willFail:fail",
                help_text="Docker image name, e.g., nginx:latest",
                max_length=200,
            ),
        ),
    ]
