# Generated by Django 5.2.8 on 2025-11-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceCatalog', '0005_instance_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('running', 'Running'),
                    ('paused', 'Paused'),
                    ('failed', 'Failed'),
                    ('stopped', 'Stopped'),
                    ('destroyed', 'Destroyed'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
    ]
