# Generated by Django 5.2.8 on 2025-11-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceCatalog', '0006_instance_slug_alter_instance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
    ]
