# Generated by Django 5.2.8 on 2025-11-14 08:30

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the module", max_length=100, unique=True
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Short description of the module"
                    ),
                ),
                (
                    "image_name",
                    models.CharField(
                        default="willFail:fail",
                        help_text="Docker image name, e.g., nginx:latest",
                        max_length=200,
                    ),
                ),
                (
                    "default_ports",
                    models.JSONField(
                        blank=True,
                        help_text="Default port mapping, e.g., {'80/tcp': 8080}",
                        null=True,
                    ),
                ),
                (
                    "default_env",
                    models.JSONField(
                        blank=True,
                        help_text="Default environment variables, e.g., {'ENV_VAR': 'value'}",
                        null=True,
                    ),
                ),
                (
                    "default_restart_policy",
                    models.JSONField(
                        blank=True,
                        help_text="Default restart policy, e.g., {'Name': 'always'}",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quota",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Maximum number of instances user can create",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Instance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for the instance",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=120)),
                (
                    "image_name",
                    models.CharField(
                        default="willFail:fail",
                        help_text="Docker image name, e.g., nginx:latest",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("failed", "Failed"),
                            ("stopped", "Stopped"),
                            ("destroyed", "Destroyed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "ports",
                    models.JSONField(
                        blank=True,
                        help_text="Port mapping used for this instance",
                        null=True,
                    ),
                ),
                (
                    "environment",
                    models.JSONField(
                        blank=True, help_text="Environment variables used", null=True
                    ),
                ),
                (
                    "restart_policy",
                    models.JSONField(
                        blank=True, help_text="Restart policy used", null=True
                    ),
                ),
                (
                    "container_id",
                    models.CharField(
                        blank=True,
                        help_text="Docker container ID",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "docker_output",
                    models.JSONField(
                        blank=True, help_text="Docker API output or metadata", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="instances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="catalog.module",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="unique_instance_name",
                        violation_error_message="This instance name is already in use.",
                    )
                ],
            },
        ),
    ]
