# Generated by Django 5.2.8 on 2025-11-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_delete_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instance",
            name="ports",
        ),
        migrations.RemoveField(
            model_name="module",
            name="default_ports",
        ),
        migrations.AddField(
            model_name="instance",
            name="container_port",
            field=models.PositiveIntegerField(
                blank=True, help_text="Container Port used for this instance", null=True
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="host_port",
            field=models.PositiveIntegerField(
                blank=True, help_text="Host Port used for this instance", null=True
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="container_port",
            field=models.PositiveIntegerField(
                blank=True, help_text="Default port mapping, e.g. 80", null=True
            ),
        ),
    ]
