# Generated by Django 5.2.8 on 2025-11-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_instance_ports_remove_module_default_ports_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instance",
            name="restart_policy",
        ),
        migrations.AddField(
            model_name="instance",
            name="default_restart_policy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no", "No"),
                    ("on-failure", "On failure"),
                    ("always", "Always"),
                    ("unless-stopped", "Unless stopped"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="default_restart_policy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no", "No"),
                    ("on-failure", "On failure"),
                    ("always", "Always"),
                    ("unless-stopped", "Unless stopped"),
                ],
                help_text="Default restart policy, e.g., {'Name': 'always'}",
                null=True,
            ),
        ),
    ]
