# Generated by Django 5.2.8 on 2025-11-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_instance_restart_policy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("paused", "Paused"),
                    ("exited", "Exited"),
                    ("stopped", "Stopped"),
                    ("destroyed", "Destroyed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
