# Generated by Django 5.2.9 on 2025-12-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0007_remove_module_default_labels_instance_pangolin_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="module_image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
