# Generated by Django 5.2.9 on 2025-12-26 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_module_module_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Instance",
        ),
    ]
