# Generated by Django 5.2.8 on 2025-11-23 15:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DockerHost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name, e.g. 'local Docker host'", max_length=100
                    ),
                ),
                (
                    "base_url",
                    models.CharField(
                        help_text="z.B. tcp://127.0.0.1:2375 or unix:///var/run/docker.sock",
                        max_length=255,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("pangolin_features", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Docker Host",
                "verbose_name_plural": "Docker Hosts",
            },
        ),
    ]
