# Generated by Django 5.2.8 on 2025-11-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerhost',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
