# Generated by Django 5.2.8 on 2025-12-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_alter_dockerhost_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerhost',
            name='default_domain',
            field=models.URLField(null=True),
        ),
    ]
